const bonusSquares = [
  { row: 0, column :0, bonus: 'triple-word' },
  { row: 0, column :7, bonus: 'triple-word' },
  { row: 0, column :14, bonus: 'triple-word' },
  { row: 7, column :0, bonus: 'triple-word' },
  { row: 7, column :14, bonus: 'triple-word' },
  { row: 14, column :0, bonus: 'triple-word' },
  { row: 14, column :7, bonus: 'triple-word' },
  { row: 14, column :14, bonus: 'triple-word' },
  { row: 1, column :1, bonus: 'double-word' },
  { row: 2, column :2, bonus: 'double-word' },
  { row: 3, column :3, bonus: 'double-word' },
  { row: 4, column :4, bonus: 'double-word' },
  { row: 1, column :13, bonus: 'double-word' },
  { row: 2, column :12, bonus: 'double-word' },
  { row: 3, column :11, bonus: 'double-word' },
  { row: 4, column :10, bonus: 'double-word' },
  { row: 10, column :4, bonus: 'double-word' },
  { row: 11, column :3, bonus: 'double-word' },
  { row: 12, column :2, bonus: 'double-word' },
  { row: 13, column :1, bonus: 'double-word' },
  { row: 10, column :10, bonus: 'double-word' },
  { row: 11, column :11, bonus: 'double-word' },
  { row: 12, column :12, bonus: 'double-word' },
  { row: 13, column :13, bonus: 'double-word' },
  { row: 1, column: 5, bonus: 'triple-letter' },
  { row: 1, column: 9, bonus: 'triple-letter' },
  { row: 13, column: 5, bonus: 'triple-letter' },
  { row: 13, column: 9, bonus: 'triple-letter' },
  { row: 5, column: 1, bonus: 'triple-letter' },
  { row: 5, column: 5, bonus: 'triple-letter' },
  { row: 5, column: 9, bonus: 'triple-letter' },
  { row: 5, column: 13, bonus: 'triple-letter' },
  { row: 9, column: 1, bonus: 'triple-letter' },
  { row: 9, column: 5, bonus: 'triple-letter' },
  { row: 9, column: 9, bonus: 'triple-letter' },
  { row: 9, column: 13, bonus: 'triple-letter' },
  { row: 1, column: 3, bonus: 'double-letter' },
  { row: 1, column: 11, bonus: 'double-letter' },
  { row: 14, column: 3, bonus: 'double-letter' },
  { row: 14, column: 11, bonus: 'double-letter' },
  { row: 2, column: 6, bonus: 'double-letter' },
  { row: 2, column: 8, bonus: 'double-letter' },
  { row: 12, column: 6, bonus: 'double-letter' },
  { row: 12, column: 8, bonus: 'double-letter' },
  { row: 3, column: 0, bonus: 'double-letter' },
  { row: 3, column: 7, bonus: 'double-letter' },
  { row: 3, column: 14, bonus: 'double-letter' },
  { row: 11, column: 0, bonus: 'double-letter' },
  { row: 11, column: 7, bonus: 'double-letter' },
  { row: 11, column: 14, bonus: 'double-letter' },
  { row: 6, column: 2, bonus: 'double-letter' },
  { row: 6, column: 6, bonus: 'double-letter' },
  { row: 6, column: 8, bonus: 'double-letter' },
  { row: 6, column: 12, bonus: 'double-letter' },
  { row: 8, column: 2, bonus: 'double-letter' },
  { row: 8, column: 6, bonus: 'double-letter' },
  { row: 8, column: 8, bonus: 'double-letter' },
  { row: 8, column: 12, bonus: 'double-letter' },
  { row: 7, column: 3, bonus: 'double-letter' },
  { row: 7, column: 11, bonus: 'double-letter' },
  { row: 7, column: 7, bonus: 'start' },
];

function determineBonus(row, column) {
    const result = bonusSquares.find(s => s.row === row && s.column === column);
    return result
      ? result.bonus
      : 'none';
}

export default determineBonus;
