import * as bonuses from '../../common/bonuses';

const bonusSquares = [
  { row: 0, column :0, bonus: bonuses.TRIPLE_WORD },
  { row: 0, column :7, bonus: bonuses.TRIPLE_WORD },
  { row: 0, column :14, bonus: bonuses.TRIPLE_WORD },
  { row: 7, column :0, bonus: bonuses.TRIPLE_WORD },
  { row: 7, column :14, bonus: bonuses.TRIPLE_WORD },
  { row: 14, column :0, bonus: bonuses.TRIPLE_WORD },
  { row: 14, column :7, bonus: bonuses.TRIPLE_WORD },
  { row: 14, column :14, bonus: bonuses.TRIPLE_WORD },
  { row: 1, column :1, bonus: bonuses.DOUBLE_WORD },
  { row: 2, column :2, bonus: bonuses.DOUBLE_WORD },
  { row: 3, column :3, bonus: bonuses.DOUBLE_WORD },
  { row: 4, column :4, bonus: bonuses.DOUBLE_WORD },
  { row: 1, column :13, bonus: bonuses.DOUBLE_WORD },
  { row: 2, column :12, bonus: bonuses.DOUBLE_WORD },
  { row: 3, column :11, bonus: bonuses.DOUBLE_WORD },
  { row: 4, column :10, bonus: bonuses.DOUBLE_WORD },
  { row: 10, column :4, bonus: bonuses.DOUBLE_WORD },
  { row: 11, column :3, bonus: bonuses.DOUBLE_WORD },
  { row: 12, column :2, bonus: bonuses.DOUBLE_WORD },
  { row: 13, column :1, bonus: bonuses.DOUBLE_WORD },
  { row: 10, column :10, bonus: bonuses.DOUBLE_WORD },
  { row: 11, column :11, bonus: bonuses.DOUBLE_WORD },
  { row: 12, column :12, bonus: bonuses.DOUBLE_WORD },
  { row: 13, column :13, bonus: bonuses.DOUBLE_WORD },
  { row: 1, column: 5, bonus: bonuses.TRIPLE_LETTER },
  { row: 1, column: 9, bonus: bonuses.TRIPLE_LETTER },
  { row: 13, column: 5, bonus: bonuses.TRIPLE_LETTER },
  { row: 13, column: 9, bonus: bonuses.TRIPLE_LETTER },
  { row: 5, column: 1, bonus: bonuses.TRIPLE_LETTER },
  { row: 5, column: 5, bonus: bonuses.TRIPLE_LETTER },
  { row: 5, column: 9, bonus: bonuses.TRIPLE_LETTER },
  { row: 5, column: 13, bonus: bonuses.TRIPLE_LETTER },
  { row: 9, column: 1, bonus: bonuses.TRIPLE_LETTER },
  { row: 9, column: 5, bonus: bonuses.TRIPLE_LETTER },
  { row: 9, column: 9, bonus: bonuses.TRIPLE_LETTER },
  { row: 9, column: 13, bonus: bonuses.TRIPLE_LETTER },
  { row: 1, column: 3, bonus: bonuses.DOUBLE_LETTER },
  { row: 1, column: 11, bonus: bonuses.DOUBLE_LETTER },
  { row: 14, column: 3, bonus: bonuses.DOUBLE_LETTER },
  { row: 14, column: 11, bonus: bonuses.DOUBLE_LETTER },
  { row: 2, column: 6, bonus: bonuses.DOUBLE_LETTER },
  { row: 2, column: 8, bonus: bonuses.DOUBLE_LETTER },
  { row: 12, column: 6, bonus: bonuses.DOUBLE_LETTER },
  { row: 12, column: 8, bonus: bonuses.DOUBLE_LETTER },
  { row: 3, column: 0, bonus: bonuses.DOUBLE_LETTER },
  { row: 3, column: 7, bonus: bonuses.DOUBLE_LETTER },
  { row: 3, column: 14, bonus: bonuses.DOUBLE_LETTER },
  { row: 11, column: 0, bonus: bonuses.DOUBLE_LETTER },
  { row: 11, column: 7, bonus: bonuses.DOUBLE_LETTER },
  { row: 11, column: 14, bonus: bonuses.DOUBLE_LETTER },
  { row: 6, column: 2, bonus: bonuses.DOUBLE_LETTER },
  { row: 6, column: 6, bonus: bonuses.DOUBLE_LETTER },
  { row: 6, column: 8, bonus: bonuses.DOUBLE_LETTER },
  { row: 6, column: 12, bonus: bonuses.DOUBLE_LETTER },
  { row: 8, column: 2, bonus: bonuses.DOUBLE_LETTER },
  { row: 8, column: 6, bonus: bonuses.DOUBLE_LETTER },
  { row: 8, column: 8, bonus: bonuses.DOUBLE_LETTER },
  { row: 8, column: 12, bonus: bonuses.DOUBLE_LETTER },
  { row: 7, column: 3, bonus: bonuses.DOUBLE_LETTER },
  { row: 7, column: 11, bonus: bonuses.DOUBLE_LETTER },
  { row: 7, column: 7, bonus: bonuses.START }
];

export const determineBonus = (row, column) => {
    const result = bonusSquares.find(s => s.row === row && s.column === column);
    return result
      ? result.bonus
      : '';
}
